#!/usr/bin/env bash
# Bash Script to setup nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello, World" | sudo tee /var/www/html/index.html
sudo service nginx start
