#!/usr/bin/env bash
#Script that redirects

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello, World" | sudo tee /var/www/html/index.html
searchingfor="^\tlocation / {"
replacewith="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;}\n\n\tlocation / {"
sudo sed -i "s@$searchingfor@$replacewith@" /etc/nginx/sites-available/default
sudo service nginx restart
