#!/usr/bin/env bash
# Install HAproxy

# Install HAproxy
sudo apt update
sudo apt install -y haproxy

# Create both blocks, append to config file
frontend="frontend myproxy
\n\tbind *:80
\n\tdefault_backend web_servers
\nbackend web_servers
\n\tbalance roundrobin
\n\tserver web-01 3.95.228.149:80 check
\n\tserver web-02 3.88.152.212:80 check"
echo -e "$frontend" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
