#!/usr/bin/env bash
#installs and configures HAPROXY

sudo apt update
sudo apt install -y haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
fefig="\nfrontend www\n\tbind *:80\n\tdefault_backend nginx_pool\n"
echo -e "$fefig" | sudo tee -a /etc/haproxy/haproxy.cfg
befig1="backend nginx_pool\n\tbalance roundrobin\n\tserver web-01 3.95.228.149:80 check"
befig2="server web-02 3.88.152.212:80 check"
echo -e "$befig1\n\t$befig2" | sudo tee -a /etc/haproxy/haproxy.cfg
